/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.leecottrell.testjframelecture;

import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author lee_c
 */
public class PlanetForm extends javax.swing.JFrame {

   
    
    public JLabel getGravityLabel() {
        return gravityLabel;
    }

    public void setGravityLabel(JLabel gravityLabel) {
        this.gravityLabel = gravityLabel;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getOrbitLabel() {
        return orbitLabel;
    }

    public void setOrbitLabel(JLabel orbitLabel) {
        this.orbitLabel = orbitLabel;
    }

    public JComboBox<String> getPlanetBox() {
        return planetBox;
    }

    public void setPlanetBox(JComboBox<String> planetBox) {
        this.planetBox = planetBox;
    }

    /**
     * Creates new form PlanetForm
     */
    
    public Planet planets[] = new Planet[9];
    public PlanetForm() {
        initComponents();
        planets[0] = new Planet("Mercury", ".1", "65");
        planets[1] = new Planet("Venus", ".2", "165");
        planets[2] = new Planet("Earth", "1", "365");
        planets[3] = new Planet("Mars", ".375", "687");
        planets[4] = new Planet("Jupiter", "0", "0");
        planets[5] = new Planet("Saturn", "0", "0");
        planets[6] = new Planet("Uranus", "0", "0");
        planets[7] = new Planet("Neptune", "0", "0");
        planets[8] = new Planet("Pluto", "0", "0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planetBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        gravityLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orbitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        planetBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto" }));
        planetBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planetBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Gravity");

        gravityLabel.setText(".375");
        gravityLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Orbit");

        orbitLabel.setText("687 Earth Days");
        orbitLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gravityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(orbitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(planetBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planetBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(gravityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(orbitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void planetBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planetBoxActionPerformed
        // TODO add your handling code here:
        
        int planetChoice = this.planetBox.getSelectedIndex();
        this.gravityLabel.setText(planets[planetChoice].getGravity());
        this.orbitLabel.setText(planets[planetChoice].getOrbit() + " Earth Days");
        
       /* String planet = this.planetBox.getSelectedItem().toString();
        if(planet.equals("Mars")){
            this.gravityLabel.setText(".375");
            this.orbitLabel.setText("687 Earth Days");
        }
        */
        
       



    
    }//GEN-LAST:event_planetBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanetForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gravityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel orbitLabel;
    private javax.swing.JComboBox<String> planetBox;
    // End of variables declaration//GEN-END:variables
}
